apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dbbrokers.gallocedrone.gallocedrone.io
spec:
  group: gallocedrone.gallocedrone.io
  names:
    kind: DbBroker
    plural: dbbrokers
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deploymentName:
              type: string
            deploymentNamespace:
              type: string
            projectID:
              type: string
          type: object
        status:
          properties:
            endPoint:
              type: string
            initialised:
              type: boolean
            username:
              type: string
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
